version: '2'
services:
  mysql:
    image: "mysql/mysql-server"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: readinglist
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  web:
    depends_on:
      - mysql
    image: "ravitella/docker-springboot-mysql:latest"
    ports:
      - "80:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/readinglist?useSSL=false
      spring.datasource.username: user
      spring.datasource.password: password
    restart: on-failure
